const jwt = require('jsonwebtoken');
const { promisify } = require('util');
const User = require(`./../models/userModel`);
const catchAsync = require(`./../utils/catchAsyncError`);
const AppError = require(`./../utils/appErrors`);
const catchAsyncError = require('./../utils/catchAsyncError');
const sendMail = require('./../utils/email')

const createToken = id => {
  return jwt.sign({ id }, process.env.JWT_SECRET, {
    expiresIn: process.env.JWT_EXPIRATION
  });
}

exports.signup = catchAsync(async (req, res, next) => {
  //console.log((new Error()).stack.split("\n")[2].trim().split(" "));
  const newUser = await User.create({
    name: req.body.name,
    email: req.body.email,
    password: req.body.password,
    passwordConf: req.body.passwordConf,
  });

  const token = createToken(newUser._id);

  res.status(201).json({
    status: `sucess`,
    token,
    user: newUser,
  });
});

exports.login = catchAsyncError(async (req, res, next) => {

  const { email, password } = req.body;
  // console.log(`login`);
  if (!email || !password) {
    return next(new AppError('Please enter a valid email address and password', 400));
  }

  const user = await User.findOne({ email }).select(`+password`);

  if (!user || !user.correctPassword(password, user.password)) {
    return next(new AppError('Please enter a valid email address and password', 400));
  };

  const token = createToken(user._id);
  res.status(200).json({
    status: `Sucess`,
    token
  })
});

exports.protect = catchAsyncError(async (req, res, next) => {
  let token;
  if (req.headers.authorization && req.headers.authorization.startsWith('Bearer')) {
    token = req.headers.authorization.split(' ')[1];
  }

  if (!token) {
    return next(new AppError('Unauthorized access, Please Login first', 401));
  }

  const decoded = await promisify(jwt.verify)(token, process.env.JWT_SECRET);
  // console.log(decoded);

  const freshUser = await User.findById(decoded.id);
  if (!freshUser) {
    return next(new AppError('User no longer exists', 401));
  }

  if (freshUser.passwordChanged(decoded.iat)) {
    // console.log(freshUser.passwordChanged(decoded.iat));
    return next(new AppError('Password changed recently, please login again', 401));
  }

  req.user = freshUser;

  next();
});

exports.restrictTo = (...roles) => {
  return (req, res, next) => {
    console.log(req.user.role)
    if (!roles.includes(req.user.role)) {
      return next(new AppError('You are not authorized for this action.', 401));
    }
    next();
  }
}

exports.forgotPassword = catchAsync(async (req, res, next) => {

  const curUser = await User.findOne({ email: req.body.email });

  if (!curUser) {
    return next(new AppError('There is no such user'), 404);
  }

  const resetToken = curUser.createPasswordResetToken();
  await curUser.save({ validateBeforeSave: false });

  const resetUrl = `${req.protocol}://${req.get('host')}/api/v1/users/resetpassword/${resetToken}`
  const message = `Use the following link to reset the passowrd of your account. \n ${resetUrl} \n If the request was not generated by you please ignore the mail`;

  try {
    await sendMail({
      email: curUser.email,
      subject: `PASSWORD RESET LINK (Valid for 10 minutes only)`,
      text: message
    })

    res.status(202).json({
      status: 'success',
      resetToken
    });

  } catch (err) {
    console.log('Mail error ' + err);
    curUser.passwordResetToken = undefined;
    curUser.passwordResetTokenValidity = undefined;
    await curUser.save({ validateBeforeSave: false });

    return next(new AppError('Our servers are facing difficulty in resolving your issue please try again later', 500))
  }
})

exports.resetPassword = catchAsyncError(async (req, res, next) => {
  res.status(500).json({
    status: "Fail",
    message: "Path not yet made"
  })
})